#!/usr/bin/env bash
# provision-ol8.sh — create KVM VMs running Oracle Linux 8 with the RHCK kernel.
#
# Usage:
#   # Provision the service-a VM (VM 0):
#   ./infra/vm/provision-ol8.sh --count 1 --name-prefix svc-a --type service-a
#
#   # Provision service-b VMs (VM 1, VM 2):
#   ./infra/vm/provision-ol8.sh --count 2 --name-prefix svc-b --type service-b
#
# VM roles:
#   service-a  — runs service-a + ebpf-agent (no nginx)
#   service-b  — runs nginx (TLS stream proxy) + service-b
#
# Kernel note:
#   OL8 cloud images boot with the Unbreakable Enterprise Kernel (UEK) by default.
#   cloud-init installs the RHCK (kernel package) and sets it as the grub default,
#   then triggers a one-time reboot. Allow ~90s for the VM to be reachable after
#   virt-install returns.
#
# Prerequisites:
#   - libvirt + virt-install + cloud-localds installed on the KVM host
#   - Oracle Linux 8 KVM cloud image downloaded to BASE_IMAGE path:
#       wget -O /var/lib/libvirt/images/ol8-cloud.qcow2 \
#           https://yum.oracle.com/templates/OracleLinux/OL8/u9/x86_64/OL8U9_x86_64-kvm-b233.qcow2
#     Check https://yum.oracle.com/oracle-linux-templates.html for the current image URL.

set -euo pipefail

# Resolve cloud-localds — may not be in sudo's restricted PATH
CLOUD_LOCALDS=$(command -v cloud-localds 2>/dev/null \
    || command -v /usr/bin/cloud-localds 2>/dev/null \
    || command -v /usr/local/bin/cloud-localds 2>/dev/null) \
    || { echo "ERROR: cloud-localds not found — install cloud-image-utils"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Defaults
COUNT=1
NAME_PREFIX="svc-b"
TYPE="service-b"           # "service-a" or "service-b"
BASE_IMAGE="/var/lib/libvirt/images/ol8-cloud.qcow2"
DISK_SIZE="10G"
RAM_MB=1024
VCPUS=2
NETWORK="br0"
IMAGE_DIR="/var/lib/libvirt/images"

# OL8 os-variant for virt-install. Use 'rhel8.6' if 'ol8.7' is not in your
# osinfo-db: osinfo-query os | grep -i oracle
OS_VARIANT="ol8.7"

usage() {
    echo "Usage: $0 [--count N] [--name-prefix PREFIX] [--type service-a|service-b] [--base-image PATH] [--network BRIDGE] [--os-variant VARIANT]"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --count)       COUNT="$2";       shift 2 ;;
        --name-prefix) NAME_PREFIX="$2"; shift 2 ;;
        --type)        TYPE="$2";        shift 2 ;;
        --base-image)  BASE_IMAGE="$2";  shift 2 ;;
        --network)     NETWORK="$2";     shift 2 ;;
        --os-variant)  OS_VARIANT="$2";  shift 2 ;;
        *) usage ;;
    esac
done

case "${TYPE}" in
    service-a) CLOUD_INIT_USERDATA="${SCRIPT_DIR}/cloud-init/user-data-ol8-service-a.yaml" ;;
    service-b) CLOUD_INIT_USERDATA="${SCRIPT_DIR}/cloud-init/user-data-ol8.yaml" ;;
    *) echo "ERROR: --type must be 'service-a' or 'service-b'"; exit 1 ;;
esac

CLOUD_INIT_META="${SCRIPT_DIR}/cloud-init/meta-data.yaml"

# Inject SSH public key into cloud-init user-data.
# Looks for ~/.ssh/id_ebpf.pub (generated by 'make setup-ssh').
SSH_PUBKEY_FILE="${HOME}/.ssh/id_ebpf.pub"
USERDATA_TMP=$(mktemp /tmp/cloud-init-userdata-XXXX.yaml)
trap 'rm -f "${USERDATA_TMP}"' EXIT

if [[ -f "${SSH_PUBKEY_FILE}" ]]; then
    PUBKEY=$(cat "${SSH_PUBKEY_FILE}")
    python3 -c "
import sys
data = open(sys.argv[1]).read()
sys.stdout.write(data.replace('EBPF_SSH_PUBKEY', sys.argv[2]))
" "${CLOUD_INIT_USERDATA}" "${PUBKEY}" > "${USERDATA_TMP}"
    echo "  Injecting SSH public key from ${SSH_PUBKEY_FILE}"
else
    python3 -c "
import sys
lines = [l for l in open(sys.argv[1]).read().splitlines() if 'EBPF_SSH_PUBKEY' not in l]
print('\n'.join(lines))
" "${CLOUD_INIT_USERDATA}" > "${USERDATA_TMP}"
    echo "  WARNING: ${SSH_PUBKEY_FILE} not found — SSH key not injected."
    echo "           Run 'make setup-ssh' after provisioning to distribute keys."
fi
CLOUD_INIT_USERDATA="${USERDATA_TMP}"

if [[ ! -f "${BASE_IMAGE}" ]]; then
    echo "ERROR: Base image not found: ${BASE_IMAGE}"
    echo "Download the Oracle Linux 8 KVM image with:"
    echo "  wget -O ${BASE_IMAGE} \\"
    echo "      https://yum.oracle.com/templates/OracleLinux/OL8/u9/x86_64/OL8U9_x86_64-kvm-b233.qcow2"
    echo "Check https://yum.oracle.com/oracle-linux-templates.html for the current URL."
    exit 1
fi

for i in $(seq 1 "${COUNT}"); do
    NAME="${NAME_PREFIX}-${i}"
    DISK="${IMAGE_DIR}/${NAME}.qcow2"
    CIDATA="${IMAGE_DIR}/${NAME}-cidata.iso"

    echo "==> Creating VM: ${NAME} (type=${TYPE}, os=${OS_VARIANT})"

    if [[ -f "${DISK}" ]]; then
        echo "  Disk ${DISK} already exists — skipping disk creation"
    else
        qemu-img create -f qcow2 -b "${BASE_IMAGE}" -F qcow2 "${DISK}" "${DISK_SIZE}"
    fi

    "${CLOUD_LOCALDS}" "${CIDATA}" "${CLOUD_INIT_USERDATA}" "${CLOUD_INIT_META}"

    virt-install \
        --name "${NAME}" \
        --ram "${RAM_MB}" \
        --vcpus "${VCPUS}" \
        --disk "${DISK},format=qcow2" \
        --disk "${CIDATA},device=cdrom" \
        --os-variant "${OS_VARIANT}" \
        --network bridge="${NETWORK}" \
        --graphics none \
        --console pty,target_type=serial \
        --noautoconsole \
        --import

    echo "  VM ${NAME} created"
done

echo ""
# OL8 cloud-init installs the RHCK kernel then reboots once — wait longer than
# the Ubuntu script to allow for that extra boot cycle.
echo "Waiting for VMs to obtain DHCP leases and complete RHCK reboot (90s)..."
sleep 90

# Prime the ARP cache with an ARP scan of the bridge subnet.
SUBNET=$(ip -4 addr show dev "${NETWORK}" 2>/dev/null \
    | awk '/inet /{print $2}')
if [[ -n "${SUBNET}" ]]; then
    if command -v nmap >/dev/null 2>&1; then
        echo "Priming ARP cache (nmap ARP scan ${SUBNET})..."
        nmap -sn "${SUBNET}" >/dev/null 2>&1 || true
        sleep 1
    else
        echo "WARN: nmap not found — install it for reliable IP detection (sudo apt-get install -y nmap)"
    fi
fi

# get_vm_ip <name>
# Tries multiple strategies to resolve the VM's IPv4 address:
#   1. qemu-guest-agent  — most reliable; requires agent to be running
#   2. ARP cache         — works on any network type; requires host has seen VM traffic
#   3. libvirt lease     — only for libvirt-managed networks (not br0)
#   4. MAC → ARP lookup  — manual ARP table scan using the VM's MAC address
get_vm_ip() {
    local name="$1"
    local ip mac

    # Filter out loopback — agent source reports all interfaces including lo
    ip=$(virsh domifaddr "${name}" --source agent 2>/dev/null \
        | awk '/ipv4/{print $4}' | cut -d/ -f1 | grep -v '^127\.')
    [[ -n "${ip}" ]] && echo "${ip}" | head -1 && return

    ip=$(virsh domifaddr "${name}" --source arp 2>/dev/null \
        | awk '/ipv4/{print $4}' | cut -d/ -f1 | grep -v '^127\.')
    [[ -n "${ip}" ]] && echo "${ip}" | head -1 && return

    ip=$(virsh domifaddr "${name}" --source lease 2>/dev/null \
        | awk '/ipv4/{print $4}' | cut -d/ -f1 | grep -v '^127\.')
    [[ -n "${ip}" ]] && echo "${ip}" | head -1 && return

    mac=$(virsh domiflist "${name}" 2>/dev/null \
        | awk '!/^-/ && !/Interface/ && NF>=5 {print $5}')
    if [[ -n "${mac}" ]]; then
        ip=$(arp -n 2>/dev/null \
            | awk -v m="${mac}" 'tolower($3)==tolower(m){print $1}')
        [[ -n "${ip}" ]] && echo "${ip}" && return
    fi

    echo ""
}

echo ""
echo "VM addresses:"
for i in $(seq 1 "${COUNT}"); do
    NAME="${NAME_PREFIX}-${i}"
    IP=$(get_vm_ip "${NAME}")
    if [[ -z "${IP}" ]]; then
        IP="<not found — try: virsh domifaddr ${NAME} --source arp>"
    fi
    echo "  ${NAME}: ${IP}"
done

echo ""
if [[ "${TYPE}" == "service-a" ]]; then
    echo "Next steps for service-a VM (OL8, user: cloud-user):"
    echo "  1. Verify RHCK:      ssh cloud-user@<ip> uname -r  (should not contain 'uek')"
    echo "  2. Deploy binaries:  make deploy-a VM_A=<ip> && make deploy-agent VM_A=<ip>"
    echo "  3. Configure VM_ADDRESSES and TLS_CA_CERT in:"
    echo "     /etc/systemd/system/service-a.service.d/override.conf"
    echo "  4. Copy CA cert:     scp certs/ca.crt cloud-user@<ip>:/etc/service-a/ca.crt"
    echo "  5. Start services:   ssh cloud-user@<ip> sudo systemctl start ebpf-agent service-a"
else
    echo "Next steps for service-b VMs (OL8, user: cloud-user):"
    echo "  1. Verify RHCK:    for each VM: ssh cloud-user@<ip> uname -r  (should not contain 'uek')"
    echo "  2. Generate certs: ./certs/gen-certs.sh <vm-ip-1> <vm-ip-2>"
    echo "  3. Deploy certs:   for each VM: scp certs/<ip>/server.{crt,key} cloud-user@<ip>:/etc/nginx/certs/"
    echo "                     ssh cloud-user@<ip> sudo systemctl restart nginx"
    echo "  4. Deploy service-b: make deploy-b VMS=\"<ip1> <ip2>\""
    echo "  5. Verify TLS:     openssl s_client -connect <vm-ip>:443 -CAfile certs/ca.crt"
fi
