// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: health/health.proto

package health

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HealthWatcherClient is the client API for HealthWatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthWatcherClient interface {
	// Watch streams health state transitions as they happen.
	// The agent pushes an event each time a connection transitions
	// between healthy and degraded (or vice versa).
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (HealthWatcher_WatchClient, error)
}

type healthWatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthWatcherClient(cc grpc.ClientConnInterface) HealthWatcherClient {
	return &healthWatcherClient{cc}
}

func (c *healthWatcherClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (HealthWatcher_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &HealthWatcher_ServiceDesc.Streams[0], "/health.HealthWatcher/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &healthWatcherWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HealthWatcher_WatchClient interface {
	Recv() (*HealthEvent, error)
	grpc.ClientStream
}

type healthWatcherWatchClient struct {
	grpc.ClientStream
}

func (x *healthWatcherWatchClient) Recv() (*HealthEvent, error) {
	m := new(HealthEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HealthWatcherServer is the server API for HealthWatcher service.
// All implementations must embed UnimplementedHealthWatcherServer
// for forward compatibility
type HealthWatcherServer interface {
	// Watch streams health state transitions as they happen.
	// The agent pushes an event each time a connection transitions
	// between healthy and degraded (or vice versa).
	Watch(*WatchRequest, HealthWatcher_WatchServer) error
	mustEmbedUnimplementedHealthWatcherServer()
}

// UnimplementedHealthWatcherServer must be embedded to have forward compatible implementations.
type UnimplementedHealthWatcherServer struct {
}

func (UnimplementedHealthWatcherServer) Watch(*WatchRequest, HealthWatcher_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedHealthWatcherServer) mustEmbedUnimplementedHealthWatcherServer() {}

// UnsafeHealthWatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthWatcherServer will
// result in compilation errors.
type UnsafeHealthWatcherServer interface {
	mustEmbedUnimplementedHealthWatcherServer()
}

func RegisterHealthWatcherServer(s grpc.ServiceRegistrar, srv HealthWatcherServer) {
	s.RegisterService(&HealthWatcher_ServiceDesc, srv)
}

func _HealthWatcher_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HealthWatcherServer).Watch(m, &healthWatcherWatchServer{stream})
}

type HealthWatcher_WatchServer interface {
	Send(*HealthEvent) error
	grpc.ServerStream
}

type healthWatcherWatchServer struct {
	grpc.ServerStream
}

func (x *healthWatcherWatchServer) Send(m *HealthEvent) error {
	return x.ServerStream.SendMsg(m)
}

// HealthWatcher_ServiceDesc is the grpc.ServiceDesc for HealthWatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthWatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health.HealthWatcher",
	HandlerType: (*HealthWatcherServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _HealthWatcher_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "health/health.proto",
}
