stream {
    upstream service_b {
        server 127.0.0.1:50051;
    }

    server {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_session_cache   shared:SSL:10m;
        ssl_session_timeout 10m;

        proxy_pass            service_b;
        proxy_timeout         3600s;
        proxy_connect_timeout 5s;
    }
}
